name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Rust toolchain (nightly)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Run benchmarks
        uses: actions-rs/cargo@v1
        with:
          command: bench