name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Rust toolchain (nightly)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Install Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Install just
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: just
      - name: Install hyperfine
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: hyperfine

      - name: Build with release profile
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Prepare benchmark data
        run: node ./generate-md.js

      - name: Run unit tests
        run: just test
      - name: Run benchmarks (reading from memory)
        run: just bench-memory
      - name: Run benchmarks (reading from file)
        run: just bench-files